### ISSUE TITLE
feat: Add invalid_target error support 

### ISSUE THREAD

**Issue by nelson-parente** [Farfetch/token-exchange#2]
The Token Exchange RFC https://www.rfc-editor.org/rfc/rfc8693.html#name-response defines that if the authorization server is unwilling or unable to issue a token for any target service indicated by the resource or audience parameters the `invalid_target` error code should be used.

The main goal of this issue is to add these validations to support this error response.

**Comment by nelson-parente** [comment]
Update: in order to solve this issue an update to the IdentityServer package is also required since the `invalid_target` isn't supported in the current version of the TokenRequestErrors enum.

https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Models/TokenRequestErrors.cs

**Comment by gsferreira** [comment]
Closing. 
The project has been archived.
#18
