### ISSUE TITLE
feat: Support may_act claim

### ISSUE THREAD

**Issue by nelson-parente** [Farfetch/token-exchange#3]
The Token Exchange RFC https://www.rfc-editor.org/rfc/rfc8693.html#name-may_act-authorized-actor-cl defines the `may_act` claim, this claim identifies who is authorized to become the actor and act on behalf of another party.

The main goal of this issue add the claim `may_act` to the framework.

**Comment by gsferreira** [comment]
Closing. 
The project has been archived.
#18
