### ISSUE TITLE
feat: Implement Impersonation Semantics

### ISSUE THREAD

**Issue by nelson-parente** [Farfetch/token-exchange#4]
The Token Exchange RFC https://www.rfc-editor.org/rfc/rfc8693.html#name-delegation-vs-impersonation defines the impersonation possibility, at this moment the framework only supports the Delegation.

Impersonation allows a principal A to impersonate principal B, A is given all the rights that B has within some defined rights context and is indistinguishable from B in that context.

This implementation will be further discussed due to security concerns.

**Comment by gsferreira** [comment]
Closing. 
The project has been archived.
#18
